on:
  push:
    branches:
    - master
jobs:
  job1:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /home/cisco/TFORM/ACI/SUPER_SIMPLE
    steps:
      - name: terraform plan
        run: terraform plan
      - name: terraform apply
        run: terraform apply -auto-approve

